// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ateftmhygiwuoqgejuge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0ZWZ0bWh5Z2l3dW9xZ2VqdWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjU5NjMsImV4cCI6MjA3MzM0MTk2M30.0x-is-mw_nWV8NkfW-CDKs0nAN4NhscYrpX5yiB6Ygk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});